### ISSUE TITLE
ERROR: 400: Invalid Input - invalid - Chrome browser management

### ISSUE THREAD

**Issue by pipilisimo** [GAM-team/GAM#1440]
I'm moving 25K enrolled browsers from the root to a sub OU. GAM gets all browsers just fine. When start moving them, I get ERROR: 400: Invalid Input - invalid. The first time it moved 5000, the second time it moved 11K. I tried batching from 100, 200, 500, and not batch command. None of these worked. Any ideas about what is going on?

**Comment by jay0lee** [comment]
You can use:

GAM_CSV_ROW_FILTER="orgUnitPath:regex:^/$" gam print browsers query
os_platform:Windows | gamd move browsers csvfile -:deviceId orgunit
/Browsers

The API doesn't let you query on current OrgUnit today so we use a local
GAM fllter to only show browsers currently in / with:

GAM_CSV_ROW_FILTER="orgUnitPath:regex:^/$"

Jay

Jay Lee

**Comment by jay0lee** [comment]
The general idea here is even if the command errors out after moving a
fraction of the browsers, when you re-run the command we won't get those
moved browsers anymore because they're already in the proper OU and not /

Just keep re-running until all / most are moved.

I suspect you may end up with a handful of browsers in the end that throw
an error when you try to move them.

Jay Lee
