### ISSUE TITLE
Error 9

### ISSUE THREAD

**Issue by kristiankruse** [GAM-team/GAM#1687]
Full steps to reproduce the issue:
1. Entering install command: `bash <(curl -s -S -L https://gam-shortn.appspot.com/gam-install)'

Expected outcome (what are you trying to do?):
* Have GAM installed

Actual outcome (what errors or bad behavior do you see instead?):
* I get a number of Pything error codes and then "ERROR: extracting the GAM archive with tar failed with error 9. Exiting."

**Comment by kristiankruse** [comment]
Forgot to add, I'm running macOS 14.5 beta 3 and using iTerm2 with latest version of Homebrew.

**Comment by fiveneins** [comment]
Hi @kristiankruse, I ran into the same error as you. You probably already figured this out, but it's possible to pull the universal Mac release and install it manually, bypassing the script.

1. `uname -m && uname -s` to confirm architecture and OS (in my case, output is "arm64 Darwin")
2. Grab the asset that corresponds from the [Releases page](https://github.com/GAM-team/GAM/releases) (in our cases, `gam-6.58-macos-universal2.tar.xz`). _Grabbing the wrong file will eventually result in the error "cannot execute binary file."_
3. Did it download to Downloads? If so: `tar -xvf ~/Downloads/gam-6.58-macos-universal2.tar.xz`
```| $ tar -xvf ~/Downloads/gam-6.58-macos-universal2.tar.xz
x gam/
x gam/LICENSE
x gam/gam
x gam/roots.pem
x gam/GamCommands.txt
```
4. Move the directory and its contents to `/usr/local/bin/` (appropriate for system-wide available scripts, not managed by system packages): `sudo mv ~/Downloads/gam /usr/local/bin/`
5. Alias gam to run it as an executable in your shell profile file: `echo $SHELL` returns `/bin/zsh` for me, so I added this line under my other aliases in `~/.zshrc`: `alias gam='/usr/local/bin/gam/gam'`
6. Don't forget to `source ~/.zshrc` or exit and reopen your terminal
7. `gam -h` should now show you that it's installed 🎉 

Hope that gets you unblocked until the bug is addressed. Cheers.

**Comment by kristiankruse** [comment]
Amazing. Thank you. Had a few zsh and bin issues along the way but worked it out. 

Thanks for your support

**Comment by ACZ83** [comment]
Hi I have just tried these steps on the official release of macOS 14.5 and get an error that gam needs to be updated by the developer - hopefully an update soon

<img width="597" alt="Screenshot 2024-05-16 at 10 08 46 AM" src="https://github.com/GAM-team/GAM/assets/168435087/5d81b5b3-6064-4873-9883-57a650f31089">

**Comment by jay0lee** [comment]
fwiw, GAM7 no longer has a universal2 build. The bash install script just detects if it's an Intel or Arm CPU and downloads/isntalls the correct GAM binaries.

Closing for now but feel free to re-open an issue if you are still seeing install issues.
