### ISSUE TITLE
Double quotes (") in HTML signature file replaced with escaped double quotes ("") upon import

### ISSUE THREAD

**Issue by BiosPlus** [GAM-team/GAM#1730]
**Description:**

I’m running into an issue where quotes (`"`) in an HTML signature file are being replaced with escaped double quotes (`""`) when applying the signature using GAM. This is causing hyperlinks and other attributes/functions (such as `style=`) to break.

---

**Checklist:**
- [x] I have upgraded to the latest GAM release from [https://github.com/GAM-team/GAM/releases](https://github.com/GAM-team/GAM/releases) and I still have this issue.
- [x] I am typing the command as described in the GAM Wiki at [https://github.com/jay0lee/gam/wiki](https://github.com/jay0lee/gam/wiki).

---

**Full Steps to Reproduce the Issue:**
1. Create an HTML file (`signature.html`) with the following content (for the purpose of testing this minimal will work fine I guess):
   ```html
   <a href="https://example.com" target="_blank">Example</a>

2. Run the following GAM command to apply the signature: `gam user first.last signature htmlfile "signature.html"`

3. Verify the applied signature using: `gam user first.last print sendas`


Here's an example of what I'm getting at the moment:
`<a href="https://www.instagram.com/redacted/" target="_blank">` becomes `<a href=""https://www.instagram.com/redacted/"" target=""_blank"">`

**Comment by taers232c** [comment]
Look closely at the output, I expect that it was actually (note the leading and trailing quotes):
"<a href="https://www.instagram.com/redacted/" target="_blank"> becomes <a href=""https://www.instagram.com/redacted/"" target=""_blank"">"

As the whole string is inside ", you have to double up the quotes on the inside so that then are not interpreted as closing the opening ".

Try this; it tells the CSV writer to use ' instead of " and now the embedded quotes do not have to be doubled.

gam config csv_output_quote_char "'"  user first.last print sendas

Ross
----
Ross Scroggs
***@***.***
